### ISSUE TITLE
Have you tried to localize anomalies on CIFAR-10 dataset with these scripts? Does it work?

### ISSUE THREAD

**Issue by MihaelG** [dbbbbm/f-AnoGAN-PyTorch#2]

**Comment by dbbbbm** [comment]
Sorry I didn't consider the problem of localization too much. But I think localization can be simply done by comparing the pixel-wise difference between the original input and output of the encoder-generator. Hope this helps！

**Comment by MihaelG** [comment]
> Sorry I didn't consider the problem of localization too much. But I think localization can be simply done by comparing the pixel-wise difference between the original input and output of the encoder-generator. Hope this helps！

Thanks for your fast response! Makes sense, I will try something like that.
