### ISSUE TITLE
Mean Squared Error in Evaluation

### ISSUE THREAD

**Issue by huberb** [dbbbbm/f-AnoGAN-PyTorch#4]
Hello, first of all thanks for this awesome implementation.

I'm looking at the file `fanogan.py` in line 247 to 252. Here's the code:

```
f_x, f_gx = netD.extract_feature(d_input).chunk(2, 0)
rec_diff = ((rec_image.view(bs, -1) - x.view(bs, -1))**2)
rec_score = rec_diff.mean(dim=1) - rec_diff.std(dim=1)
feat_diff = ((f_x - f_gx)**2)
feat_score = feat_diff.mean(dim=1) + feat_diff.std(dim=1)
outlier_score = rec_score + options.alpha * feat_score
```

This looks like the mean squared error to me, which makes sense since that is used in the paper.
However, I don't really understand why you subtract the standard deviation from the mean error.
Also, the deviation is added to the mean error of extracted features.
I've tested this and i've seen that the tensor `rec_score` holds negative values, which would not be possible with the mean squared error as it is implemented in for example `sklearn.metrics`. However, using the standard deviation raises my ROC score from 0.91 to 0.93. Could you give me a hint why the deviation is included at all?

**Comment by dbbbbm** [comment]
Thanks for pointing it out. It was my mistake that I forgot to remove the std part from the code. My intuition was that the anomalies would have higher standard deviation in the squared difference so I added them to the score. But it didn't seem to work so I gave up this idea.

**Comment by huberb** [comment]
Great, that clears it up :) thanks again for the awesome project
