### ISSUE TITLE
Why use Adam optimizer for encoder training instead of RMSprop?

### ISSUE THREAD

**Issue by diviramon** [dbbbbm/f-AnoGAN-PyTorch#5]
The official Tensorflow implementation uses RMSprop for the encoder training, however in this implementation the same adam optimizer used for WGAN training is used for the encoder. Was there a specific reason why?

Thanks!

**Comment by dbbbbm** [comment]
Hi, 

There is no such reason. I used Adam in the beginning and it just works for me. You can try to used RMSprop. I'm sorry if the codes make you confused.
